trigger:
- master
- develop
pr:
- master
- develop

stages:
- stage: A
  displayName: 'SDK'
  jobs:
  - job: A1
    displayName: 'Linux Build'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - script: | 
        sudo mv /usr/local/bin/cmake /usr/local/bin/cmake-old
        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 8611B7A28669BB93
        sudo apt-add-repository 'deb https://apt.kitware.com/ubuntu/ xenial main'
        sudo apt-get update && sudo apt-get install -y cmake
        cmake --version
      displayName: 'Upgrade cmake'
    - task: CMake@1
      displayName: 'Config'
      inputs:
        workingDirectory: $(Build.SourcesDirectory)
        cmakeArgs: '-S . -B build'
    - task: CMake@1
      displayName: 'Build'
      inputs:
        workingDirectory: $(Build.SourcesDirectory)
        cmakeArgs: '--build build'
    - script: | 
        ElectionGuard_DIR="$(Build.SourcesDirectory)/build/ElectionGuard" cmake -S examples/simple -B simple_build
        cmake --build simple_build --target simple
      displayName: 'Build Simple Election'
    - script: | 
        cd simple_build
        ./simple
      displayName: 'Test Simple Election'