name: Pull Request

on: [pull_request]

jobs:
  linux_build:
    name: 'Linux Build'
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Upgrade cmake
      run: | 
        sudo mv /usr/local/bin/cmake /usr/local/bin/cmake-old
        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 8611B7A28669BB93
        sudo apt-add-repository 'deb https://apt.kitware.com/ubuntu/ xenial main'
        sudo apt-get update && sudo apt-get install -y cmake
        cmake --version
    - name: Build C Library
      run: |
        cmake --version
        cmake -S . -B build
        cmake --build build
    - name: 'Build API Sample Election'
      run: | 
        ElectionGuard_DIR="$PWD/build/ElectionGuard" cmake -S examples/api -B api_build
        cmake --build api_build --target api
    - name: 'Test API Sample Election'
      run: | 
        cd api_build
        ./api
  windows_build:
    name: 'Windows Build'
    runs-on: 'windows-latest'
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Install msys
      run: |
        $msyspath="msys64"
        choco install msys2 --params="/InstallDir:$msyspath /NoPath" -y
        echo "::add-path::$msyspath\usr\bin"
        echo "::add-path::$msyspath"
        echo "::add-path::$msyspath\mingw64\bin"
        echo "::add-path::$msyspath\mingw64\lib"
        echo "::add-path::$msyspath\mingw64\include"
    - name: Install gcc and gmp
      run: |
        pacman --noconfirm -Syu
        pacman --noconfirm -S mingw-w64-x86_64-gcc mingw-w64-x86_64-gmp
    - name: Build C Library
      run: |
        cmake --version
        cmake -S . -B build -G "MSYS Makefiles"
        cmake --build build
    - name: 'Build API Sample Election'
      run: |
        $env:CMAKE_PREFIX_PATH="./build/ElectionGuard"
        cmake -S examples/api -B api_build -G "MSYS Makefiles"
        cmake --build api_build --target api
    - name: 'Test API Sample Election'
      run: | 
        $env:Path+=";.\build\"
        $outcome = Invoke-Expression ".\api_build\api.exe"
        echo $outcome
  macos_build:
    name: 'MacOS Build'
    runs-on: 'macOS-latest'
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Install gmp
      run: |
        brew install gmp
        echo "::add-path::/usr/local/lib"
        echo "::add-path::/usr/local/include"
    - name: Build C Library
      run: |
        cmake --version
        cmake -S . -B build
        cmake --build build
    - name: 'Build API Sample Election'
      run: | 
        ElectionGuard_DIR="$PWD/build/ElectionGuard" cmake -S examples/api -B api_build
        cmake --build api_build --target api
    - name: 'Test API Sample Election'
      run: | 
        cd api_build
        ./api